//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config"
import react from "eslint-plugin-react"
import reactHooks from "eslint-plugin-react-hooks"
import jsxA11y from "eslint-plugin-jsx-a11y"

// components/ui/ is shadcn-vendored (regenerated by the shadcn CLI, not
// hand-maintained) — same reasoning as leaving it untouched in the folder
// reorganization. React/hooks/a11y rules skip it: prop-types is simply
// wrong for a TypeScript project's own components but doubly so for
// vendored ones, and its interactive-wrapper patterns (e.g.
// InputGroupAddon's click-to-focus convenience) are established primitive
// behavior, not app-level bugs to fix here.
const UI_GLOB = "**/components/ui/**"

export default [
  ...tanstackConfig,
  // React/JSX/hooks/a11y linting — none of this existed before. jsx-runtime
  // is spread after recommended so it wins the react-in-jsx-scope /
  // jsx-uses-react overrides (React 19's automatic JSX runtime needs neither).
  {
    files: ["**/*.{jsx,tsx}"],
    ignores: [UI_GLOB],
    ...react.configs.flat.recommended,
  },
  {
    files: ["**/*.{jsx,tsx}"],
    ignores: [UI_GLOB],
    ...react.configs.flat["jsx-runtime"],
  },
  {
    files: ["**/*.{jsx,tsx}"],
    ignores: [UI_GLOB],
    ...reactHooks.configs["recommended-latest"],
  },
  {
    files: ["**/*.{jsx,tsx}"],
    ignores: [UI_GLOB],
    ...jsxA11y.flatConfigs.recommended,
  },
  {
    // Airbnb rule values not already covered by the recommended configs
    // above, curated against this project's own conventions: nothing here
    // fights Prettier's semi:false/double-quote formatting, and
    // import/prefer-default-export is deliberately not adopted — route
    // files (export const Route) and most components use named exports on
    // purpose, and Airbnb's default-export preference would fight that on
    // every file in routes/.
    files: ["**/*.{jsx,tsx}"],
    ignores: [UI_GLOB],
    rules: {
      "react/no-array-index-key": "warn",
      "react/self-closing-comp": "error",
      "react/jsx-boolean-value": ["error", "never"],
      // This codebase's UI copy leans on plain-English contractions
      // constantly ("doesn't", "isn't", "you'll") — enforcing &apos;/&rsquo;
      // escapes would make every explanatory string harder to read for a
      // rule whose original purpose (catching a stray `>` that reads like
      // markup) modern JSX parsers already handle safely for straight quotes.
      "react/no-unescaped-entities": "off",
      // allowAsProps: this codebase's dominant "component defined during
      // render" shape is a TanStack Table column's `cell: (props) => <jsx/>`
      // render-prop (and the equivalent Recharts formatter/content props) —
      // a value passed as a prop, invoked by the library's own render
      // machinery, not a component actually mounted into the JSX tree. The
      // rule's real target (a component declared and then rendered as
      // `<Inner/>` inside its parent, remounting every render) still errors.
      "react/no-unstable-nested-components": ["error", { allowAsProps: true }],
      // Every autoFocus in this app is on the first field of a form the
      // admin/holder is looking at right when it appears (login email, OTP
      // digit entry, passcode setup/verify, an edit dialog's first input) —
      // a deliberate, low-risk UX choice already made throughout the app,
      // not something worth reverting file by file. Downgraded rather than
      // silenced outright, so a genuinely surprising new use still shows up.
      "jsx-a11y/no-autofocus": "warn",
      "prefer-destructuring": ["warn", { object: true, array: false }],
      "object-shorthand": "warn",
      "no-else-return": "warn",
      "no-param-reassign": [
        "error",
        { props: true, ignorePropertyModificationsFor: [] },
      ],
    },
  },
  {
    rules: {
      "import/no-cycle": "off",
      "import/order": "off",
      "sort-imports": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/require-await": "off",
      "pnpm/json-enforce-catalog": "off",
    },
  },
  {
    ignores: ["eslint.config.js", ".prettierrc"],
  },
]
