/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as OrderRouteImport } from './routes/order'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminVerifyOtpRouteImport } from './routes/admin/verify-otp'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminOrdersRouteImport } from './routes/_authed/admin/orders'
import { Route as AuthedAdminOverviewRouteImport } from './routes/_authed/admin/overview'
import { Route as AuthedAdminSettingsRouteImport } from './routes/_authed/admin/settings'
import { Route as UsersKeysStatusSlugRouteImport } from './routes/users/keys-status.$slug'
import { Route as UsersLoginSlugRouteImport } from './routes/users/login.$slug'
import { Route as UsersSetupSlugRouteImport } from './routes/users/setup.$slug'
import { Route as AuthedAdminKeysKeyIdRouteImport } from './routes/_authed/admin/keys.$keyId'
import { Route as AuthedAdminRevenueIndexRouteImport } from './routes/_authed/admin/revenue.index'
import { Route as AuthedAdminRevenueServerIdRouteImport } from './routes/_authed/admin/revenue.$serverId'
import { Route as AuthedAdminServersIndexRouteImport } from './routes/_authed/admin/servers.index'
import { Route as AuthedAdminServersServerIdRouteImport } from './routes/_authed/admin/servers.$serverId'
import { Route as AuthedAdminUsersIndexRouteImport } from './routes/_authed/admin/users.index'
import { Route as AuthedAdminUsersUserIdRouteImport } from './routes/_authed/admin/users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifyOtpRoute = AdminVerifyOtpRouteImport.update({
  id: '/admin/verify-otp',
  path: '/admin/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminOrdersRoute = AuthedAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminOverviewRoute = AuthedAdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminSettingsRoute = AuthedAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const UsersKeysStatusSlugRoute = UsersKeysStatusSlugRouteImport.update({
  id: '/users/keys-status/$slug',
  path: '/users/keys-status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersLoginSlugRoute = UsersLoginSlugRouteImport.update({
  id: '/users/login/$slug',
  path: '/users/login/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersSetupSlugRoute = UsersSetupSlugRouteImport.update({
  id: '/users/setup/$slug',
  path: '/users/setup/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminKeysKeyIdRoute = AuthedAdminKeysKeyIdRouteImport.update({
  id: '/admin/keys/$keyId',
  path: '/admin/keys/$keyId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminRevenueIndexRoute = AuthedAdminRevenueIndexRouteImport.update({
  id: '/admin/revenue/',
  path: '/admin/revenue/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminRevenueServerIdRoute =
  AuthedAdminRevenueServerIdRouteImport.update({
    id: '/admin/revenue/$serverId',
    path: '/admin/revenue/$serverId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAdminServersIndexRoute = AuthedAdminServersIndexRouteImport.update({
  id: '/admin/servers/',
  path: '/admin/servers/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminServersServerIdRoute =
  AuthedAdminServersServerIdRouteImport.update({
    id: '/admin/servers/$serverId',
    path: '/admin/servers/$serverId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAdminUsersIndexRoute = AuthedAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminUsersUserIdRoute = AuthedAdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/verify-otp': typeof AdminVerifyOtpRoute
  '/admin/orders': typeof AuthedAdminOrdersRoute
  '/admin/overview': typeof AuthedAdminOverviewRoute
  '/admin/settings': typeof AuthedAdminSettingsRoute
  '/users/keys-status/$slug': typeof UsersKeysStatusSlugRoute
  '/users/login/$slug': typeof UsersLoginSlugRoute
  '/users/setup/$slug': typeof UsersSetupSlugRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/admin/keys/$keyId': typeof AuthedAdminKeysKeyIdRoute
  '/admin/revenue/$serverId': typeof AuthedAdminRevenueServerIdRoute
  '/admin/servers/$serverId': typeof AuthedAdminServersServerIdRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/admin/revenue/': typeof AuthedAdminRevenueIndexRoute
  '/admin/servers/': typeof AuthedAdminServersIndexRoute
  '/admin/users/': typeof AuthedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order': typeof OrderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/verify-otp': typeof AdminVerifyOtpRoute
  '/admin/orders': typeof AuthedAdminOrdersRoute
  '/admin/overview': typeof AuthedAdminOverviewRoute
  '/admin/settings': typeof AuthedAdminSettingsRoute
  '/users/keys-status/$slug': typeof UsersKeysStatusSlugRoute
  '/users/login/$slug': typeof UsersLoginSlugRoute
  '/users/setup/$slug': typeof UsersSetupSlugRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/admin/keys/$keyId': typeof AuthedAdminKeysKeyIdRoute
  '/admin/revenue/$serverId': typeof AuthedAdminRevenueServerIdRoute
  '/admin/servers/$serverId': typeof AuthedAdminServersServerIdRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/admin/revenue': typeof AuthedAdminRevenueIndexRoute
  '/admin/servers': typeof AuthedAdminServersIndexRoute
  '/admin/users': typeof AuthedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/order': typeof OrderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/verify-otp': typeof AdminVerifyOtpRoute
  '/_authed/admin/orders': typeof AuthedAdminOrdersRoute
  '/_authed/admin/overview': typeof AuthedAdminOverviewRoute
  '/_authed/admin/settings': typeof AuthedAdminSettingsRoute
  '/users/keys-status/$slug': typeof UsersKeysStatusSlugRoute
  '/users/login/$slug': typeof UsersLoginSlugRoute
  '/users/setup/$slug': typeof UsersSetupSlugRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/admin/keys/$keyId': typeof AuthedAdminKeysKeyIdRoute
  '/_authed/admin/revenue/$serverId': typeof AuthedAdminRevenueServerIdRoute
  '/_authed/admin/servers/$serverId': typeof AuthedAdminServersServerIdRoute
  '/_authed/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/_authed/admin/revenue/': typeof AuthedAdminRevenueIndexRoute
  '/_authed/admin/servers/': typeof AuthedAdminServersIndexRoute
  '/_authed/admin/users/': typeof AuthedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/order'
    | '/admin/login'
    | '/admin/verify-otp'
    | '/admin/orders'
    | '/admin/overview'
    | '/admin/settings'
    | '/users/keys-status/$slug'
    | '/users/login/$slug'
    | '/users/setup/$slug'
    | '/admin/'
    | '/admin/keys/$keyId'
    | '/admin/revenue/$serverId'
    | '/admin/servers/$serverId'
    | '/admin/users/$userId'
    | '/admin/revenue/'
    | '/admin/servers/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/order'
    | '/admin/login'
    | '/admin/verify-otp'
    | '/admin/orders'
    | '/admin/overview'
    | '/admin/settings'
    | '/users/keys-status/$slug'
    | '/users/login/$slug'
    | '/users/setup/$slug'
    | '/admin'
    | '/admin/keys/$keyId'
    | '/admin/revenue/$serverId'
    | '/admin/servers/$serverId'
    | '/admin/users/$userId'
    | '/admin/revenue'
    | '/admin/servers'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/order'
    | '/admin/login'
    | '/admin/verify-otp'
    | '/_authed/admin/orders'
    | '/_authed/admin/overview'
    | '/_authed/admin/settings'
    | '/users/keys-status/$slug'
    | '/users/login/$slug'
    | '/users/setup/$slug'
    | '/_authed/admin/'
    | '/_authed/admin/keys/$keyId'
    | '/_authed/admin/revenue/$serverId'
    | '/_authed/admin/servers/$serverId'
    | '/_authed/admin/users/$userId'
    | '/_authed/admin/revenue/'
    | '/_authed/admin/servers/'
    | '/_authed/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  OrderRoute: typeof OrderRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminVerifyOtpRoute: typeof AdminVerifyOtpRoute
  UsersKeysStatusSlugRoute: typeof UsersKeysStatusSlugRoute
  UsersLoginSlugRoute: typeof UsersLoginSlugRoute
  UsersSetupSlugRoute: typeof UsersSetupSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verify-otp': {
      id: '/admin/verify-otp'
      path: '/admin/verify-otp'
      fullPath: '/admin/verify-otp'
      preLoaderRoute: typeof AdminVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/orders': {
      id: '/_authed/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthedAdminOrdersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/overview': {
      id: '/_authed/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthedAdminOverviewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/settings': {
      id: '/_authed/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthedAdminSettingsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/users/keys-status/$slug': {
      id: '/users/keys-status/$slug'
      path: '/users/keys-status/$slug'
      fullPath: '/users/keys-status/$slug'
      preLoaderRoute: typeof UsersKeysStatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/login/$slug': {
      id: '/users/login/$slug'
      path: '/users/login/$slug'
      fullPath: '/users/login/$slug'
      preLoaderRoute: typeof UsersLoginSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/setup/$slug': {
      id: '/users/setup/$slug'
      path: '/users/setup/$slug'
      fullPath: '/users/setup/$slug'
      preLoaderRoute: typeof UsersSetupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/keys/$keyId': {
      id: '/_authed/admin/keys/$keyId'
      path: '/admin/keys/$keyId'
      fullPath: '/admin/keys/$keyId'
      preLoaderRoute: typeof AuthedAdminKeysKeyIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/revenue/': {
      id: '/_authed/admin/revenue/'
      path: '/admin/revenue'
      fullPath: '/admin/revenue/'
      preLoaderRoute: typeof AuthedAdminRevenueIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/revenue/$serverId': {
      id: '/_authed/admin/revenue/$serverId'
      path: '/admin/revenue/$serverId'
      fullPath: '/admin/revenue/$serverId'
      preLoaderRoute: typeof AuthedAdminRevenueServerIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/servers/': {
      id: '/_authed/admin/servers/'
      path: '/admin/servers'
      fullPath: '/admin/servers/'
      preLoaderRoute: typeof AuthedAdminServersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/servers/$serverId': {
      id: '/_authed/admin/servers/$serverId'
      path: '/admin/servers/$serverId'
      fullPath: '/admin/servers/$serverId'
      preLoaderRoute: typeof AuthedAdminServersServerIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/users/': {
      id: '/_authed/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/users/$userId': {
      id: '/_authed/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedAdminOrdersRoute: typeof AuthedAdminOrdersRoute
  AuthedAdminOverviewRoute: typeof AuthedAdminOverviewRoute
  AuthedAdminSettingsRoute: typeof AuthedAdminSettingsRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminKeysKeyIdRoute: typeof AuthedAdminKeysKeyIdRoute
  AuthedAdminRevenueServerIdRoute: typeof AuthedAdminRevenueServerIdRoute
  AuthedAdminServersServerIdRoute: typeof AuthedAdminServersServerIdRoute
  AuthedAdminUsersUserIdRoute: typeof AuthedAdminUsersUserIdRoute
  AuthedAdminRevenueIndexRoute: typeof AuthedAdminRevenueIndexRoute
  AuthedAdminServersIndexRoute: typeof AuthedAdminServersIndexRoute
  AuthedAdminUsersIndexRoute: typeof AuthedAdminUsersIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAdminOrdersRoute: AuthedAdminOrdersRoute,
  AuthedAdminOverviewRoute: AuthedAdminOverviewRoute,
  AuthedAdminSettingsRoute: AuthedAdminSettingsRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminKeysKeyIdRoute: AuthedAdminKeysKeyIdRoute,
  AuthedAdminRevenueServerIdRoute: AuthedAdminRevenueServerIdRoute,
  AuthedAdminServersServerIdRoute: AuthedAdminServersServerIdRoute,
  AuthedAdminUsersUserIdRoute: AuthedAdminUsersUserIdRoute,
  AuthedAdminRevenueIndexRoute: AuthedAdminRevenueIndexRoute,
  AuthedAdminServersIndexRoute: AuthedAdminServersIndexRoute,
  AuthedAdminUsersIndexRoute: AuthedAdminUsersIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  OrderRoute: OrderRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminVerifyOtpRoute: AdminVerifyOtpRoute,
  UsersKeysStatusSlugRoute: UsersKeysStatusSlugRoute,
  UsersLoginSlugRoute: UsersLoginSlugRoute,
  UsersSetupSlugRoute: UsersSetupSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
