/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminVerifyOtpRouteImport } from './routes/admin.verify-otp'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed.admin.index'
import { Route as AuthedAdminOverviewRouteImport } from './routes/_authed.admin.overview'
import { Route as AuthedAdminRevenueRouteImport } from './routes/_authed.admin.revenue'
import { Route as UsersKeysStatusSlugRouteImport } from './routes/users.keys-status.$slug'
import { Route as UsersLoginSlugRouteImport } from './routes/users.login.$slug'
import { Route as UsersSetupSlugRouteImport } from './routes/users.setup.$slug'
import { Route as AuthedAdminKeysKeyIdRouteImport } from './routes/_authed.admin.keys.$keyId'
import { Route as AuthedAdminServersIndexRouteImport } from './routes/_authed.admin.servers.index'
import { Route as AuthedAdminServersServerIdRouteImport } from './routes/_authed.admin.servers.$serverId'
import { Route as AuthedAdminUsersIndexRouteImport } from './routes/_authed.admin.users.index'
import { Route as AuthedAdminUsersUserIdRouteImport } from './routes/_authed.admin.users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifyOtpRoute = AdminVerifyOtpRouteImport.update({
  id: '/admin/verify-otp',
  path: '/admin/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminOverviewRoute = AuthedAdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRevenueRoute = AuthedAdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => AuthedRoute,
} as any)
const UsersKeysStatusSlugRoute = UsersKeysStatusSlugRouteImport.update({
  id: '/users/keys-status/$slug',
  path: '/users/keys-status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersLoginSlugRoute = UsersLoginSlugRouteImport.update({
  id: '/users/login/$slug',
  path: '/users/login/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersSetupSlugRoute = UsersSetupSlugRouteImport.update({
  id: '/users/setup/$slug',
  path: '/users/setup/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminKeysKeyIdRoute = AuthedAdminKeysKeyIdRouteImport.update({
  id: '/admin/keys/$keyId',
  path: '/admin/keys/$keyId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminServersIndexRoute = AuthedAdminServersIndexRouteImport.update({
  id: '/admin/servers/',
  path: '/admin/servers/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminServersServerIdRoute =
  AuthedAdminServersServerIdRouteImport.update({
    id: '/admin/servers/$serverId',
    path: '/admin/servers/$serverId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminUsersIndexRoute = AuthedAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsersUserIdRoute = AuthedAdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/verify-otp': typeof AdminVerifyOtpRoute
  '/admin/overview': typeof AuthedAdminOverviewRoute
  '/admin/revenue': typeof AuthedAdminRevenueRoute
  '/users/keys-status/$slug': typeof UsersKeysStatusSlugRoute
  '/users/login/$slug': typeof UsersLoginSlugRoute
  '/users/setup/$slug': typeof UsersSetupSlugRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/admin/keys/$keyId': typeof AuthedAdminKeysKeyIdRoute
  '/admin/servers/$serverId': typeof AuthedAdminServersServerIdRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/admin/servers/': typeof AuthedAdminServersIndexRoute
  '/admin/users/': typeof AuthedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/verify-otp': typeof AdminVerifyOtpRoute
  '/admin/overview': typeof AuthedAdminOverviewRoute
  '/admin/revenue': typeof AuthedAdminRevenueRoute
  '/users/keys-status/$slug': typeof UsersKeysStatusSlugRoute
  '/users/login/$slug': typeof UsersLoginSlugRoute
  '/users/setup/$slug': typeof UsersSetupSlugRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/admin/keys/$keyId': typeof AuthedAdminKeysKeyIdRoute
  '/admin/servers/$serverId': typeof AuthedAdminServersServerIdRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/admin/servers': typeof AuthedAdminServersIndexRoute
  '/admin/users': typeof AuthedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/verify-otp': typeof AdminVerifyOtpRoute
  '/_authed/admin/overview': typeof AuthedAdminOverviewRoute
  '/_authed/admin/revenue': typeof AuthedAdminRevenueRoute
  '/users/keys-status/$slug': typeof UsersKeysStatusSlugRoute
  '/users/login/$slug': typeof UsersLoginSlugRoute
  '/users/setup/$slug': typeof UsersSetupSlugRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/admin/keys/$keyId': typeof AuthedAdminKeysKeyIdRoute
  '/_authed/admin/servers/$serverId': typeof AuthedAdminServersServerIdRoute
  '/_authed/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/_authed/admin/servers/': typeof AuthedAdminServersIndexRoute
  '/_authed/admin/users/': typeof AuthedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/admin/verify-otp'
    | '/admin/overview'
    | '/admin/revenue'
    | '/users/keys-status/$slug'
    | '/users/login/$slug'
    | '/users/setup/$slug'
    | '/admin/'
    | '/admin/keys/$keyId'
    | '/admin/servers/$serverId'
    | '/admin/users/$userId'
    | '/admin/servers/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin/verify-otp'
    | '/admin/overview'
    | '/admin/revenue'
    | '/users/keys-status/$slug'
    | '/users/login/$slug'
    | '/users/setup/$slug'
    | '/admin'
    | '/admin/keys/$keyId'
    | '/admin/servers/$serverId'
    | '/admin/users/$userId'
    | '/admin/servers'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/admin/login'
    | '/admin/verify-otp'
    | '/_authed/admin/overview'
    | '/_authed/admin/revenue'
    | '/users/keys-status/$slug'
    | '/users/login/$slug'
    | '/users/setup/$slug'
    | '/_authed/admin/'
    | '/_authed/admin/keys/$keyId'
    | '/_authed/admin/servers/$serverId'
    | '/_authed/admin/users/$userId'
    | '/_authed/admin/servers/'
    | '/_authed/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminVerifyOtpRoute: typeof AdminVerifyOtpRoute
  UsersKeysStatusSlugRoute: typeof UsersKeysStatusSlugRoute
  UsersLoginSlugRoute: typeof UsersLoginSlugRoute
  UsersSetupSlugRoute: typeof UsersSetupSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verify-otp': {
      id: '/admin/verify-otp'
      path: '/admin/verify-otp'
      fullPath: '/admin/verify-otp'
      preLoaderRoute: typeof AdminVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/overview': {
      id: '/_authed/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthedAdminOverviewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/revenue': {
      id: '/_authed/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AuthedAdminRevenueRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/users/keys-status/$slug': {
      id: '/users/keys-status/$slug'
      path: '/users/keys-status/$slug'
      fullPath: '/users/keys-status/$slug'
      preLoaderRoute: typeof UsersKeysStatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/login/$slug': {
      id: '/users/login/$slug'
      path: '/users/login/$slug'
      fullPath: '/users/login/$slug'
      preLoaderRoute: typeof UsersLoginSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/setup/$slug': {
      id: '/users/setup/$slug'
      path: '/users/setup/$slug'
      fullPath: '/users/setup/$slug'
      preLoaderRoute: typeof UsersSetupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/keys/$keyId': {
      id: '/_authed/admin/keys/$keyId'
      path: '/admin/keys/$keyId'
      fullPath: '/admin/keys/$keyId'
      preLoaderRoute: typeof AuthedAdminKeysKeyIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/servers/': {
      id: '/_authed/admin/servers/'
      path: '/admin/servers'
      fullPath: '/admin/servers/'
      preLoaderRoute: typeof AuthedAdminServersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/servers/$serverId': {
      id: '/_authed/admin/servers/$serverId'
      path: '/admin/servers/$serverId'
      fullPath: '/admin/servers/$serverId'
      preLoaderRoute: typeof AuthedAdminServersServerIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users/': {
      id: '/_authed/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users/$userId': {
      id: '/_authed/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminOverviewRoute: typeof AuthedAdminOverviewRoute
  AuthedAdminRevenueRoute: typeof AuthedAdminRevenueRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminKeysKeyIdRoute: typeof AuthedAdminKeysKeyIdRoute
  AuthedAdminServersServerIdRoute: typeof AuthedAdminServersServerIdRoute
  AuthedAdminUsersUserIdRoute: typeof AuthedAdminUsersUserIdRoute
  AuthedAdminServersIndexRoute: typeof AuthedAdminServersIndexRoute
  AuthedAdminUsersIndexRoute: typeof AuthedAdminUsersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminOverviewRoute: AuthedAdminOverviewRoute,
  AuthedAdminRevenueRoute: AuthedAdminRevenueRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminKeysKeyIdRoute: AuthedAdminKeysKeyIdRoute,
  AuthedAdminServersServerIdRoute: AuthedAdminServersServerIdRoute,
  AuthedAdminUsersUserIdRoute: AuthedAdminUsersUserIdRoute,
  AuthedAdminServersIndexRoute: AuthedAdminServersIndexRoute,
  AuthedAdminUsersIndexRoute: AuthedAdminUsersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminVerifyOtpRoute: AdminVerifyOtpRoute,
  UsersKeysStatusSlugRoute: UsersKeysStatusSlugRoute,
  UsersLoginSlugRoute: UsersLoginSlugRoute,
  UsersSetupSlugRoute: UsersSetupSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
